### ISSUE TITLE
helm install not working Error: template:

### ISSUE THREAD

**Issue by outbackdingo** [Skeen/helm-bitwarden_rs#11]
Error: template: bitwarden/templates/ingress.yaml:43:20: executing "bitwarden/templates/ingress.yaml" at <.Capabilities.APIVersions.Has>: can't evaluate field Capabilities in type interface {}

kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:10:22Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}

**Comment by sebtiz13** [comment]
Hello have you retry after update `kubectl` or `helm` ?
For me, I haven't error

```shell
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"archive", BuildDate:"2022-09-22T10:08:42Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
```
```shell
$ helm version
version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.19.1"}
```

**Comment by outbackdingo** [comment]
LOL over 1 year later.... pass!
